package com.souklemdina.myapp;

import com.codename1.db.Cursor;
import com.codename1.db.Database;
import com.codename1.db.Row;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;

import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.souklemdina.gui.Home;
import com.souklemdina.gui.ToolBarCustom;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
     Resources theme;
     Database db;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }

         try{ 
         db= Database.openOrCreate("souklemdina");
        db.execute(" Create table if not exists ProduitPanier(id INTEGER PRIMARY KEY,idProduit integer,quantite integer,prix double);");
        
        // System.out.println("success");
         }
         
         catch(IOException ex){
             System.out.println(ex);}
        //hi.show();
        Home h = new Home();
        ToolBarCustom tbs = new ToolBarCustom();
        h.setF(tbs.Customize(h.getF(), theme));
        //h.getF().getToolbar().addCommandToSideMenu("test", null, null);
        h.getF().show();

    }

    
    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
